#include "stdint.h"

#define bvnot(x) (~(x))
#define bvand(x, y) ((x) & (y))
#define bvor(x, y) ((x) | (y))
#define bvredor(x) (!!(x))
#define bvxor(x, y) ((x) ^ (y))
#define bvadd(x, y) ((x) + (y))
#define bvsub(x, y) ((x) - (y))
#define bvneg(x) (-(x))
#define bvshl(x, y) ((x) << (y))
#define bvshr(x, y) ((x) >> (y))
#define bvule(x, y) (((uint32_t) (x)) <= ((uint32_t) (y)))
#define bvuge(x, y) (((uint32_t) (x)) >= ((uint32_t) (y)))
#define bvugt(x, y) (((uint32_t) (x)) > ((uint32_t) (y)))
#define bveq(x, y) ((x) == (y))
#define bvmul(x, y) ((x) * (y))
#define bvdiv(x, y) ((x) / (y))
